[package]
name = "xorRust"
version = "0.1.0"
authors = ["Wesley Ryder <wr140815@ohio.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
